export const FormData = {
  eventLanguage: "ar",
  oneSupervisorOrTrainerForEvent: true,
  eventType: "",
  startDate: "",
  endDate: "",
  capacity: "",
  registeredNumber: "",
  supervisorId: "",
  date: "",
  place: "",
  trainerId: "",
  courseId: "",
  startDateRes: "",
  endDateRes: "",
  startExamDate: "",
  endExamDate: "",
  eventName: "",
  eventNameEn: "",
  productId: "",
};