name: Android Builder

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  capBuild:
    name: Build Repo with Capacitor
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build APK
        run: cd android && ./gradlew assembleDebug

      - name: Rename APK
        run: mv android/app/build/outputs/apk/debug/app-debug.apk android/app/build/outputs/apk/debug/LMS.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: LMS.apk
          path: android/app/build/outputs/apk/debug/LMS.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: android/app/build/outputs/apk/debug/LMS.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}